export interface Logradouro {
  code: string;
  name: string;
}


export const LOGRADOUROS: Logradouro[] = [
  { code: "001", name: "Acesso" },
  { code: "002", name: "Adro" },
  { code: "004", name: "Alameda" },
  { code: "005", name: "Alto" },
  { code: "007", name: "Atalho" },
  { code: "008", name: "Avenida" },
  { code: "009", name: "Balneario" },
  { code: "010", name: "Belvedere" },
  { code: "011", name: "Beco" },
  { code: "012", name: "Bloco" },
  { code: "013", name: "Bosque" },
  { code: "014", name: "Boulevard" },
  { code: "015", name: "Baixa" },
  { code: "016", name: "Cais" },
  { code: "017", name: "Caminho" },
  { code: "019", name: "Chapadão" },
  { code: "020", name: "Conjunto" },
  { code: "021", name: "Colônia" },
  { code: "022", name: "Corredor" },
  { code: "023", name: "Campo" },
  { code: "024", name: "Córrego" },
  { code: "027", name: "Desvio" },
  { code: "028", name: "Distrito" },
  { code: "030", name: "Escada" },
  { code: "031", name: "Estrada" },
  { code: "032", name: "Estação" },
  { code: "033", name: "Estádio" },
  { code: "036", name: "Favela" },
  { code: "037", name: "Fazenda" },
  { code: "038", name: "Ferrovia" },
  { code: "039", name: "Fonte" },
  { code: "040", name: "Feira" },
  { code: "043", name: "Forte" },
  { code: "045", name: "Galeria" },
  { code: "046", name: "Granja" },
  { code: "050", name: "Ilha" },
  { code: "052", name: "Jardim" },
  { code: "053", name: "Ladeira" },
  { code: "054", name: "Largo" },
  { code: "055", name: "Lagoa" },
  { code: "056", name: "Loteamento" },
  { code: "059", name: "Morro" },
  { code: "060", name: "Monte" },
  { code: "062", name: "Paralela" },
  { code: "063", name: "Passeio" },
  { code: "064", name: "Pátio" },
  { code: "065", name: "Praça" },
  { code: "067", name: "Parada" },
  { code: "070", name: "Praia" },
  { code: "071", name: "Prolongamento" },
  { code: "072", name: "Parque" },
  { code: "073", name: "Passarela" },
  { code: "074", name: "Passagem" },
  { code: "076", name: "Ponte" },
  { code: "077", name: "Quadra" },
  { code: "079", name: "Quinta" },
  { code: "081", name: "Rua" },
  { code: "082", name: "Ramal" },
  { code: "087", name: "Recanto" },
  { code: "088", name: "Retiro" },
  { code: "089", name: "Reta" },
  { code: "090", name: "Rodovia" },
  { code: "091", name: "Retorno" },
  { code: "092", name: "Sítio" },
  { code: "094", name: "Servidão" },
  { code: "095", name: "Setor" },
  { code: "096", name: "Subida" },
  { code: "097", name: "Trincheira" },
  { code: "098", name: "Terminal" },
  { code: "099", name: "Trevo" },
  { code: "100", name: "Travessa" },
  { code: "101", name: "Via" },
  { code: "103", name: "Viaduto" },
  { code: "104", name: "Vila" },
  { code: "105", name: "Viela" },
  { code: "106", name: "Vale" },
  { code: "108", name: "Zigue-zague" },
  { code: "452", name: "Trecho" },
  { code: "453", name: "Vereda" },
  { code: "465", name: "Artéria" },
  { code: "468", name: "Elevada" },
  { code: "469", name: "Porto" },
  { code: "470", name: "Balão" },
  { code: "471", name: "Paradouro" },
  { code: "472", name: "Área" },
  { code: "473", name: "Jardinete" },
  { code: "474", name: "Esplanada" },
  { code: "475", name: "Quintas" },
  { code: "476", name: "Rotula" },
  { code: "477", name: "Marina" },
  { code: "478", name: "Descida" },
  { code: "479", name: "Circular" },
  { code: "480", name: "Unidade" },
  { code: "481", name: "Chácara" },
  { code: "482", name: "Rampa" },
  { code: "483", name: "Ponta" },
  { code: "484", name: "Via de pedestre" },
  { code: "485", name: "Condomínio" },
  { code: "486", name: "Habitacional" },
  { code: "487", name: "Residencial" },
  { code: "495", name: "Canal" },
  { code: "496", name: "Buraco" },
  { code: "497", name: "Módulo" },
  { code: "498", name: "Estância" },
  { code: "499", name: "Lago" },
  { code: "500", name: "Núcleo" },
  { code: "501", name: "Aeroporto" },
  { code: "502", name: "Passagem Subterrânea" },
  { code: "503", name: "Complexo Viário" },
  { code: "504", name: "Praça de Esportes" },
  { code: "505", name: "Via Elevada" },
  { code: "506", name: "Rotatória" },
  { code: "507", name: "1ª Travessa" },
  { code: "508", name: "2ª Travessa" },
  { code: "509", name: "3ª Travessa" },
  { code: "510", name: "4ª Travessa" },
  { code: "511", name: "5ª Travessa" },
  { code: "512", name: "6ª Travessa" },
  { code: "513", name: "7ª Travessa" },
  { code: "514", name: "8ª Travessa" },
  { code: "515", name: "9ª Travessa" },
  { code: "516", name: "10ª Travessa" },
  { code: "517", name: "11ª Travessa" },
  { code: "518", name: "12ª Travessa" },
  { code: "519", name: "13ª Travessa" },
  { code: "520", name: "14ª Travessa" },
  { code: "521", name: "15ª Travessa" },
  { code: "522", name: "16ª Travessa" },
  { code: "523", name: "1º Alto" },
  { code: "524", name: "2º Alto" },
  { code: "525", name: "3º Alto" },
  { code: "526", name: "4º Alto" },
  { code: "527", name: "5º Alto" },
  { code: "528", name: "1º Beco" },
  { code: "529", name: "2º Beco" },
  { code: "530", name: "3º Beco" },
  { code: "531", name: "4º Beco" },
  { code: "532", name: "5º Beco" },
  { code: "533", name: "1ª Paralela" },
  { code: "534", name: "2ª Paralela" },
  { code: "535", name: "3ª Paralela" },
  { code: "536", name: "4ª Paralela" },
  { code: "537", name: "5ª Paralela" },
  { code: "538", name: "1ª Subida" },
  { code: "539", name: "2ª Subida" },
  { code: "540", name: "3ª Subida" },
  { code: "541", name: "4ª Subida" },
  { code: "542", name: "5ª Subida" },
  { code: "543", name: "6ª Subida" },
  { code: "544", name: "1ª Vila" },
  { code: "545", name: "2ª Vila" },
  { code: "546", name: "3ª Vila" },
  { code: "547", name: "4ª Vila" },
  { code: "548", name: "5ª Vila" },
  { code: "549", name: "1º Parque" },
  { code: "550", name: "2º Parque" },
  { code: "551", name: "3º Parque" },
  { code: "552", name: "1ª Rua" },
  { code: "553", name: "2ª Rua" },
  { code: "554", name: "3ª Rua" },
  { code: "555", name: "4ª Rua" },
  { code: "556", name: "5ª Rua" },
  { code: "557", name: "6ª Rua" },
  { code: "558", name: "7ª Rua" },
  { code: "559", name: "8ª Rua" },
  { code: "560", name: "9ª Rua" },
  { code: "561", name: "10ª Rua" },
  { code: "562", name: "11ª Rua" },
  { code: "563", name: "12ª Rua" },
  { code: "564", name: "Estacionamento" },
  { code: "565", name: "Vala" },
  { code: "566", name: "Rua de Pedestre" },
  { code: "567", name: "Túnel" },
  { code: "568", name: "Variante" },
  { code: "569", name: "Rodo Anel" },
  { code: "570", name: "Travessa Particular" },
  { code: "571", name: "Calçada" },
  { code: "572", name: "Via de Acesso" },
  { code: "573", name: "Entrada Particular" },
  { code: "645", name: "Acampamento" },
  { code: "646", name: "Via Expressa" },
];
