# Generated by Django 5.2.1 on 2025-06-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_establishment',
        ),
    ]
