# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_remove_customuser_active_establishment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usuarios',
        ),
    ]
