# Generated by Django 5.2.1 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_alter_citymodel_name'),
        ('customuser', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='city.citymodel', verbose_name='Cidade'),
        ),
    ]
