# Generated by Django 5.2.1 on 2025-08-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_citymodel_agency_name_citymodel_ibge_code'),
        ('customuser', '0005_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='city.citymodel', verbose_name='Cidade'),
        ),
    ]
