# Generated by Django 5.2.1 on 2025-06-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0010_delete_procedurerecordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='procedure.proceduremodel')),
            ],
            options={
                'db_table': 'procedures_record',
            },
        ),
    ]
