# Generated by Django 5.2.1 on 2025-06-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0001_initial'),
        ('procedure_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerecordmodel',
            name='apac_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='apac_data.apacdatamodel'),
            preserve_default=False,
        ),
    ]
