# Generated by Django 5.2.1 on 2025-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0002_alter_apacdatamodel_apac_request'),
        ('procedure_record', '0002_procedurerecordmodel_apac_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurerecordmodel',
            name='apac_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='apac_data.apacdatamodel'),
        ),
    ]
