# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_record', '0003_alter_procedurerecordmodel_apac_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procedurerecordmodel',
            table='prodecimentos_apac_registros',
        ),
    ]
