# Generated by Django 5.2.1 on 2026-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_record', '0005_alter_procedurerecordmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerecordmodel',
            name='cbo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Cbo do médico executante'),
        ),
        migrations.AddField(
            model_name='procedurerecordmodel',
            name='cnes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cnes do estabelecimento executante'),
        ),
    ]
