# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apac_request', '0002_alter_apacrequestmodel_authorizer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apacrequestmodel',
            table='solicitacoes_apac',
        ),
    ]
