# Generated by Django 5.2.1 on 2025-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_request', '0005_alter_apacrequestmodel_authorizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacrequestmodel',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da análise'),
        ),
        migrations.AlterField(
            model_name='apacrequestmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização'),
        ),
    ]
