# Generated by Django 5.2.1 on 2025-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_request', '0006_alter_apacrequestmodel_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacrequestmodel',
            name='request_date',
            field=models.DateField(verbose_name='Data da solicitação'),
        ),
    ]
