# Generated by Django 5.2.1 on 2025-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_request', '0007_alter_apacrequestmodel_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacrequestmodel',
            name='request_date',
            field=models.DateField(verbose_name='Competência'),
        ),
    ]
