# Generated by Django 5.2.1 on 2025-05-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('customuser', '0001_initial'),
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityModel',
        ),
    ]
