# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_rename_city_citymodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citymodel',
            table='cidades',
        ),
    ]
