# Generated by Django 5.2.1 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_citymodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
    ]
