# Generated by Django 5.2.1 on 2025-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_citymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da cidade'),
        ),
    ]
