# Generated by Django 5.2.1 on 2025-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_alter_citymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Agencia'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='ibge_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código do IBGE'),
        ),
    ]
