# Generated by Django 5.2.1 on 2025-08-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_citymodel_agency_name_citymodel_ibge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='agency_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Nome Agencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='ibge_code',
            field=models.CharField(default='...', max_length=255, verbose_name='Código do IBGE'),
            preserve_default=False,
        ),
    ]
