# Generated by Django 5.2.1 on 2025-06-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apac_request', '0001_initial'),
        ('procedure', '0010_delete_procedurerecordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_record_number', models.CharField(max_length=255)),
                ('patient_cns', models.CharField(max_length=255)),
                ('patient_cpf', models.CharField(max_length=255)),
                ('patient_birth_date', models.CharField(max_length=255)),
                ('patient_race_color', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(max_length=255)),
                ('patient_mother_name', models.CharField(max_length=255)),
                ('patient_address_street_type', models.CharField(max_length=255)),
                ('patient_address_street_name', models.CharField(max_length=255)),
                ('patient_address_number', models.CharField(max_length=255)),
                ('patient_address_complement', models.CharField(max_length=255)),
                ('patient_address_postal_code', models.CharField(max_length=255)),
                ('patient_address_neighborhood', models.CharField(max_length=255)),
                ('patient_address_city', models.CharField(max_length=255)),
                ('patient_address_state', models.CharField(max_length=255)),
                ('medicName', models.CharField(max_length=255)),
                ('medicCns', models.CharField(max_length=255)),
                ('medicCbo', models.CharField(max_length=255)),
                ('apac_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apac_data', to='apac_request.apacrequestmodel')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.cidmodel')),
                ('main_procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.proceduremodel')),
            ],
        ),
    ]
