# Generated by Django 5.2.1 on 2025-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0001_initial'),
        ('apac_request', '0002_alter_apacrequestmodel_authorizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apac_data', to='apac_request.apacrequestmodel'),
        ),
    ]
