# Generated by Django 5.2.1 on 2025-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0002_alter_apacdatamodel_apac_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacdatamodel',
            name='procedure_date',
            field=models.CharField(default=0.08333333333333333, max_length=255),
            preserve_default=False,
        ),
    ]
