# Generated by Django 5.2.1 on 2025-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0003_apacdatamodel_procedure_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apacdatamodel',
            old_name='medicCbo',
            new_name='medic_cbo',
        ),
        migrations.RenameField(
            model_name='apacdatamodel',
            old_name='medicCns',
            new_name='medic_cns',
        ),
        migrations.RenameField(
            model_name='apacdatamodel',
            old_name='medicName',
            new_name='medic_name',
        ),
    ]
