# Generated by Django 5.2.1 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0005_alter_apacdatamodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apacdatamodel',
            options={'verbose_name': 'Dado Apac', 'verbose_name_plural': 'Dados Apac'},
        ),
    ]
