# Generated by Django 5.2.1 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0006_alter_apacdatamodel_options'),
        ('apac_request', '0005_alter_apacrequestmodel_authorizer_and_more'),
        ('procedure', '0013_alter_cidmodel_code_alter_cidmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apac_data', to='apac_request.apacrequestmodel', verbose_name='Solcitação APAC'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.cidmodel', verbose_name='CID'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='main_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedure.proceduremodel', verbose_name='Procedimento principal'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='medic_cbo',
            field=models.CharField(max_length=255, verbose_name='CBO do médico'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='medic_cns',
            field=models.CharField(max_length=255, verbose_name='CNS do médico'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='medic_name',
            field=models.CharField(max_length=255, verbose_name='Nome do médico'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_city',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_complement',
            field=models.CharField(max_length=255, verbose_name='Complemento do endereço'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_neighborhood',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_number',
            field=models.CharField(max_length=255, verbose_name='Número do endereço'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_postal_code',
            field=models.CharField(max_length=255, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_state',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_street_name',
            field=models.CharField(max_length=255, verbose_name='Nome do logradouro'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_street_type',
            field=models.CharField(max_length=255, verbose_name='Tipo de logradouro'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_birth_date',
            field=models.CharField(max_length=255, verbose_name='Data de nascimento do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_cns',
            field=models.CharField(max_length=255, verbose_name='CNS do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_cpf',
            field=models.CharField(max_length=255, verbose_name='CPF do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_gender',
            field=models.CharField(max_length=255, verbose_name='Gênero do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_mother_name',
            field=models.CharField(max_length=255, verbose_name='Nome da mãe do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_name',
            field=models.CharField(max_length=255, verbose_name='Nome do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_race_color',
            field=models.CharField(max_length=255, verbose_name='Raça/cor do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_record_number',
            field=models.CharField(max_length=255, verbose_name='Número do prontuário'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='procedure_date',
            field=models.CharField(max_length=255, verbose_name='Data do procedimento'),
        ),
    ]
