# Generated by Django 5.2.1 on 2025-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0007_alter_apacdatamodel_apac_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_birth_date',
            field=models.DateField(verbose_name='Data de nascimento do paciente'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='procedure_date',
            field=models.DateField(verbose_name='Data do procedimento'),
        ),
    ]
