# Generated by Django 5.2.1 on 2025-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0008_alter_apacdatamodel_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apacdatamodel',
            name='medic_cbo',
        ),
        migrations.RemoveField(
            model_name='apacdatamodel',
            name='medic_cns',
        ),
        migrations.RemoveField(
            model_name='apacdatamodel',
            name='medic_name',
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='authorizing_physician_cbo',
            field=models.CharField(default=123456, max_length=255, verbose_name='CBO do médico autorizador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='authorizing_physician_cns',
            field=models.CharField(default=123456, max_length=255, verbose_name='CNS do médico autorizador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='authorizing_physician_name',
            field=models.CharField(default='daniel', max_length=255, verbose_name='Nome do médico autorizador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='supervising_physician_cbo',
            field=models.CharField(default=123456, max_length=255, verbose_name='CBO do médico responsavel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='supervising_physician_cns',
            field=models.CharField(default=123456, max_length=255, verbose_name='CNS do médico responsavel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacdatamodel',
            name='supervising_physician_name',
            field=models.CharField(default='daniel', max_length=255, verbose_name='Nome do médico responsavel'),
            preserve_default=False,
        ),
    ]
