# Generated by Django 5.2.1 on 2025-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0009_remove_apacdatamodel_medic_cbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacdatamodel',
            name='discharge_date',
            field=models.DateField(default='2025-05-29', verbose_name='Data da alta'),
            preserve_default=False,
        ),
    ]
