# Generated by Django 5.2.1 on 2025-08-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0010_apacdatamodel_discharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento do endereço'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_record_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do prontuário'),
        ),
    ]
