# Generated by Django 5.2.1 on 2025-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0011_alter_apacdatamodel_patient_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_address_complement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Complemento do endereço'),
        ),
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_record_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Número do prontuário'),
        ),
    ]
