# Generated by Django 5.2.1 on 2025-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0012_alter_apacdatamodel_patient_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacdatamodel',
            name='patient_race_color',
            field=models.CharField(choices=[('01', 'Branca'), ('02', 'Preta'), ('03', 'Parda'), ('04', 'Amarela'), ('05', 'Indígena'), ('06', 'Sem informação')], max_length=2, verbose_name='Raça/cor do paciente'),
        ),
    ]
