# Generated by Django 5.2.1 on 2026-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0013_alter_apacdatamodel_patient_race_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacdatamodel',
            name='diagnostic_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Diagonóstico'),
        ),
    ]
