# Generated by Django 5.2.1 on 2026-09-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_data', '0015_alter_apacdatamodel_patient_address_street_type'),
        ('procedure', '0026_cidmodel_secondary_of_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacdatamodel',
            name='secondary_cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procedure.cidmodel', verbose_name='CID de causas associadas'),
        ),
    ]
