# Generated by Django 5.2.1 on 2025-05-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_rename_city_citymodel'),
        ('customuser', '0001_initial'),
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Establishment',
            new_name='EstablishmentModel',
        ),
    ]
