# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_rename_establishment_establishmentmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='establishmentmodel',
            table='estabelecimentos',
        ),
    ]
