# Generated by Django 5.2.1 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_alter_establishmentmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishmentmodel',
            options={'verbose_name': 'Estabelecimentp', 'verbose_name_plural': 'Estabelecimentos'},
        ),
    ]
