# Generated by Django 5.2.1 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_alter_citymodel_name'),
        ('establishment', '0004_alter_establishmentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='city.citymodel', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='establishmentmodel',
            name='cnes',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cnes Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='establishmentmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está Ativo'),
        ),
        migrations.AlterField(
            model_name='establishmentmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Estabelecimento'),
        ),
    ]
