# Generated by Django 5.2.1 on 2025-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0005_alter_establishmentmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentmodel',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='establishmentmodel',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
    ]
