# Generated by Django 5.2.1 on 2025-08-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_establishmentmodel_acronym_establishmentmodel_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='acronym',
            field=models.CharField(default='...', max_length=255, verbose_name='Sigla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establishmentmodel',
            name='cnpj',
            field=models.CharField(default='...', max_length=14, verbose_name='CNPJ'),
            preserve_default=False,
        ),
    ]
