# Generated by Django 5.2.1 on 2025-11-13 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_alter_establishmentmodel_acronym_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishmentmodel',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AddField(
            model_name='establishmentmodel',
            name='restricted_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Restringir visualização'),
        ),
    ]
