# Generated by Django 5.2.1 on 2026-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_alter_establishmentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='cnes',
            field=models.CharField(max_length=15, verbose_name='Cnes Estabelecimento'),
        ),
    ]
