# Generated by Django 5.2.1 on 2025-06-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apac_request', '0001_initial'),
        ('city', '0002_rename_city_citymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=255)),
                ('created_in', models.DateField(auto_now_add=True)),
                ('expire_in', models.DateField(blank=True, null=True)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('apac_request', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apac_request', to='apac_request.apacrequestmodel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.citymodel')),
            ],
        ),
    ]
