# Generated by Django 5.2.1 on 2025-06-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0001_initial'),
        ('apac_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apac_request', to='apac_request.apacrequestmodel'),
        ),
    ]
