# Generated by Django 5.2.1 on 2025-06-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0002_alter_apacbatchmodel_apac_request'),
        ('apac_request', '0002_alter_apacrequestmodel_authorizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apac_batch', to='apac_request.apacrequestmodel'),
        ),
    ]
