# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0003_alter_apacbatchmodel_apac_request'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apacbatchmodel',
            table='faixas_apac',
        ),
    ]
