# Generated by Django 5.2.1 on 2025-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0004_alter_apacbatchmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='batch_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
