# Generated by Django 5.2.1 on 2025-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0005_alter_apacbatchmodel_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='expire_in',
            field=models.DateField(),
        ),
    ]
