# Generated by Django 5.2.1 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0006_alter_apacbatchmodel_expire_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apacbatchmodel',
            options={'verbose_name': 'Faixa Apac', 'verbose_name_plural': 'Faixas Apac'},
        ),
    ]
