# Generated by Django 5.2.1 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0007_alter_apacbatchmodel_options'),
        ('apac_request', '0005_alter_apacrequestmodel_authorizer_and_more'),
        ('city', '0005_alter_citymodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apacbatchmodel',
            options={'verbose_name': 'Lote Apac', 'verbose_name_plural': 'Lotes Apac'},
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apac_batch', to='apac_request.apacrequestmodel', verbose_name='Requisição APAC'),
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='batch_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número do lote'),
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.citymodel', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='created_in',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='expire_in',
            field=models.DateField(verbose_name='Data de expiração'),
        ),
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='export_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de exportação'),
        ),
    ]
