# Generated by Django 5.2.1 on 2025-06-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apac_batch', '0008_alter_apacbatchmodel_options_and_more'),
        ('apac_request', '0005_alter_apacrequestmodel_authorizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacbatchmodel',
            name='apac_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apac_batch', to='apac_request.apacrequestmodel', verbose_name='Requisição APAC'),
        ),
    ]
