# Generated by Django 5.2.1 on 2025-05-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_procedurerecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedure',
            new_name='ProcedureModel',
        ),
        migrations.RenameModel(
            old_name='ProcedureRecord',
            new_name='ProcedureRecordModel',
        ),
    ]
