# Generated by Django 5.2.1 on 2025-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_rename_procedure_proceduremodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduremodel',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
