# Generated by Django 5.2.1 on 2025-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_proceduremodel_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremodel',
            name='code',
            field=models.CharField(db_column='cod_sig_tap', max_length=20),
        ),
    ]
