# Generated by Django 5.2.1 on 2025-06-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_alter_proceduremodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='cod_sig_tap', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='procedure.proceduremodel')),
            ],
        ),
    ]
