# Generated by Django 5.2.1 on 2025-06-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_cid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cid',
            new_name='CidModel',
        ),
    ]
