# Generated by Django 5.2.1 on 2025-06-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_rename_cid_cidmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidmodel',
            table='cid',
        ),
    ]
