# Generated by Django 5.2.1 on 2025-06-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0008_alter_cidmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurerecordmodel',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='procedure.proceduremodel'),
        ),
    ]
