# Generated by Django 5.2.1 on 2025-06-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0009_alter_procedurerecordmodel_procedure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcedureRecordModel',
        ),
    ]
