# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_delete_procedurerecordmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proceduremodel',
            table='procedimentos',
        ),
    ]
