# Generated by Django 5.2.1 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0011_alter_proceduremodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduremodel',
            options={'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
    ]
