# Generated by Django 5.2.1 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_alter_proceduremodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidmodel',
            name='code',
            field=models.CharField(db_column='cod_sig_tap', max_length=20, verbose_name='Código CID'),
        ),
        migrations.AlterField(
            model_name='cidmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome CID'),
        ),
        migrations.AlterField(
            model_name='cidmodel',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='procedure.proceduremodel', verbose_name='Procedimento'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='code',
            field=models.CharField(db_column='cod_sig_tap', max_length=20, verbose_name='Código do Procedimento'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Procedimento'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Procedimento'),
        ),
        migrations.AlterField(
            model_name='proceduremodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='procedure.proceduremodel', verbose_name='Procedimento Pai'),
        ),
    ]
