# Generated by Django 5.2.1 on 2025-06-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0013_alter_cidmodel_code_alter_cidmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidmodel',
            options={'verbose_name': 'Cid', 'verbose_name_plural': 'Cids'},
        ),
    ]
