# Generated by Django 5.2.1 on 2025-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0014_alter_cidmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
    ]
