# Generated by Django 5.2.1 on 2025-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0015_cidmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Procedimento'),
        ),
    ]