# Generated by Django 5.2.1 on 2025-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0016_alter_proceduremodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduremodel',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children_recovery', to='procedure.proceduremodel'),
        ),
    ]
