# Generated by Django 5.2.1 on 2025-09-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_proceduremodel_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduremodel',
            name='parent',
        ),
    ]
