# Generated by Django 5.2.1 on 2025-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0018_remove_proceduremodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome CID'),
        ),
    ]
