# Generated by Django 5.2.1 on 2025-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0019_alter_cidmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidmodel',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='cids', to='procedure.proceduremodel'),
        ),
    ]
