# Generated by Django 5.2.1 on 2025-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0020_cidmodel_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidmodel',
            name='code',
            field=models.CharField(db_column='cod_cid', max_length=20, verbose_name='Código CID'),
        ),
    ]
