# Generated by Django 5.2.1 on 2025-11-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0021_alter_cidmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidmodel',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='procedure.proceduremodel', verbose_name='Procedimento'),
        ),
    ]
