# Generated by Django 5.2.1 on 2025-11-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0022_alter_cidmodel_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidmodel',
            name='procedure',
        ),
    ]
