# Generated by Django 5.2.1 on 2025-11-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0023_remove_cidmodel_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidmodel',
            old_name='parents',
            new_name='procedure',
        ),
    ]
