# Generated by Django 5.2.1 on 2026-07-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0024_rename_parents_cidmodel_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduremodel',
            name='fixed_validity_two_competences',
            field=models.BooleanField(default=False, help_text='Atributo SIGTAP 054. Marque se o APAC Magnético exigir validade de 2 competências para este procedimento (erro 010087). Sem marcar, a validade exportada é a padrão de 3 competências.', verbose_name='Validade fixa de 2 competências'),
        ),
    ]
