# Generated by Django 5.2.1 on 2026-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0025_proceduremodel_fixed_validity_two_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidmodel',
            name='secondary_of_procedure',
            field=models.ManyToManyField(blank=True, related_name='secondary_cids', to='procedure.proceduremodel'),
        ),
        migrations.AddField(
            model_name='proceduremodel',
            name='requires_secondary_cid',
            field=models.BooleanField(default=False, help_text='Atributo SIGTAP 043. Marque se o APAC Magnético exigir um segundo CID (causas associadas) para este procedimento.', verbose_name='Exige CID de causas associadas'),
        ),
    ]
