# Generated by Django 5.2.1 on 2026-09-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0026_cidmodel_secondary_of_procedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Atributo SIGTAP PAPA_QTMAX. Vazio = sem limite conhecido cadastrado.', null=True, verbose_name='Quantidade máxima')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='procedure.proceduremodel', verbose_name='Procedimento secundário')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_links', to='procedure.proceduremodel', verbose_name='Procedimento principal')),
            ],
            options={
                'verbose_name': 'Procedimento secundário',
                'verbose_name_plural': 'Procedimentos secundários',
                'db_table': 'procedimentos_secundarios',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
