# Generated by Django 5.2.1 on 2026-09-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0028_copiar_parents_para_procedure_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduremodel',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='proceduremodel',
            name='parents',
        ),
    ]
