# Generated by Django 5.2.1 on 2026-09-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0029_remove_proceduremodel_mandatory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_code', models.CharField(help_text='Código de rastreabilidade (057, 067, 068, 069, 070...), não usado em lógica.', max_length=3, verbose_name='Atributo complementar SIGTAP')),
                ('description', models.CharField(help_text='Texto oficial da portaria, mostrado ao usuário no formulário.', max_length=255, verbose_name='Descrição da regra')),
                ('minimum', models.PositiveIntegerField(default=1, verbose_name='Quantidade mínima')),
                ('members', models.ManyToManyField(related_name='requirement_group_memberships', to='procedure.proceduremodel', verbose_name='Procedimentos que satisfazem a exigência')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='procedure.proceduremodel', verbose_name='Procedimento principal')),
            ],
            options={
                'verbose_name': 'Grupo de exigência alternativa',
                'verbose_name_plural': 'Grupos de exigência alternativa',
                'db_table': 'procedimentos_grupos_exigencia',
            },
        ),
    ]
