# Generated by Django 5.2.1 on 2026-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0030_procedurerequirementgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduremodel',
            name='pmae',
            field=models.BooleanField(default=False, help_text='Atributo SIGTAP 053 (Agora Tem Especialistas). Marque para exigir no mínimo 2 secundários, sendo um deles consulta ou teleconsulta. Toda OCI tem este atributo.', verbose_name='Procedimento PMAE'),
        ),
    ]
